baseURL: https://leksuss.github.io/leks.us/
languageCode: en-us
title: Python, English

theme: photophobia

disableKinds: RSS
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 10
googleAnalytics: ""

sitemap:
  changefreq: daily
  priority: 0.5
  filename: sitemap.xml

params:
  favicon: null
  site_logo: null
  description: Notes from Python & Django developer
  recent_posts_number: 10

markup:
  highlight:
    style: native
